modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/Blobanium/EnhancedPacketCompression/issues"
license = "MIT"

[[mods]]
modId = "enhancedpacketcompression"
version = "${version}"
displayName = "Enhanced Packet Compression"
authors = "Blobanium"
description = '''

'''
#logoFile = ""

[[dependencies.enhancedpacketcompression]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.enhancedpacketcompression]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.enhancedpacketcompression]]
modId = "architectury"
type = "required"
versionRange = "[11.1.17,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "enhancedpacketcompression.mixins.json"
